### ISSUE TITLE
Docker images now provided by infinit

### ISSUE THREAD

**Issue by mefyl** [geo-data/infinit-docker#1]
Hi there; I just stumbled upon this repository, thanks for helping improve the Infinit ecosystem!

I just wanted to notify that our CI now pushes images onto the docker public hub at https://hub.docker.com/r/mefyl/infinit, so you could use this directly to always get the latest releases - `mefyl/infinit:0.7.0` as we speak.

Cheers,

**Comment by ivanstegic** [comment]
@mefyl Thank you for posting this. Is this the official Infinit docker image? Would love to see the Dockerfile config but the image isn't linked to a github repo :(

**Comment by mefyl** [comment]
We are in the process of open sourcing the whole thing, but the Dockerfile is not available yet. However it wouldn't be of much use to you as it basically takes the output of our CI and `COPY` it inside the container. It is indeed the official image (CTO at Infinit), we're working with docker towards getting it on hub.docker.com/_/infinit soon.

**Comment by giminni** [comment]
@mefyl where can I find the raspberry output? In your official image I found only x86_64 with and without symlinks.
